#!/system/bin/sh
#=======================================#
#VARIABLES===============================#
BB=/data/adb/magisk/busybox
BRANCH="4-Revert_To_Stock"
#=======================================#
#=======================================#

sleep 2

$BB rm -rf /data/vendor/dolby/dax_sqlite3.db

pm clear com.oneplus.sound.tuner

$BB rm -rf /data/adb/modules/se-xtreme

$BB rm -rf /data/media/0/YourSEchanges.log

sleep 5
reboot
